version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQLDB_DATABASE}
    volumes:
      - db:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=db
      - PMA_USER=root
      - PMA_PASSWORD=${MYSQLDB_ROOT_PASSWORD}
  api:
    depends_on:
      - db
    build:
      context: ./backend-api
      dockerfile: Dockerfile
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_HOST=db
      - DB_USER=${MYSQLDB_USER}
      - DB_PASS=${MYSQLDB_USER_PASS}
      - DB_NAME=${MYSQLDB_DATABASE}
      - DB_PORT=3306
  ui:
    depends_on: 
       - api
    build:
      context: ./frontend-vue
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    environment:
      - VUE_APP_API_HOST=<your server ip-adress>:3000
volumes:
  db: